### ISSUE TITLE
No such file or directory ./wait-for-selenium.sh

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3718]
Hi everyone, 

I've followed this tutorial: https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657

While running **docker-compose up -d --build && docker-compose down** I get this error: 

ERROR: for dfc4708ab537_instapy-master_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./wait-for-selenium.sh\": stat ./wait-for-selenium.sh: no such file or directory": unknown

Any clues how to rectify it?

**Comment by filo87** [comment]
Hi All,

Same problem here on Debian stretch. Everything worked fine until pulling the last repo version. 

Running **docker-compose up -d --build** produces the following errors:

```
ERROR: for instapy_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"./wait-for-selenium.sh\": stat ./wait-for-selenium.sh: no such file or directory": unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"./wait-for-selenium.sh\": stat ./wait-for-selenium.sh: no such file or directory": unknown

ERROR: Encountered errors while bringing up the project. 
```

However by using  **docker-compose -f"docker-dev.yml" up -d --build** with the production docker-compose it works fine.

**Comment by filo87** [comment]
Seems like i found the issue... the last merge request #3711 modified the Dockerfile. 
docker-compose.yml needs to be updated accordingly!

Substitute your docker-compose.yml with the following:
```
version: '3'
services:
  web:
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./:/code
    command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "/code/docker_quickst$
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
```

and it should work fine!

**Comment by ghost** [comment]
> Seems like i found the issue... the last merge request #3711 modified the Dockerfile.
> docker-compose.yml needs to be updated accordingly!
> 
> Substitute your docker-compose.yml with the following:
> 
> ```
> version: '3'
> services:
>   web:
>     environment:
>       - PYTHONUNBUFFERED=0
>     build:
>       context: .
>       dockerfile: ./docker_conf/python/Dockerfile
>     depends_on:
>       - selenium
>     volumes:
>       - ./:/code
>     command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "/code/docker_quickst$
>   selenium:
>     container_name: selenium
>     image: selenium/standalone-chrome-debug
>     ports:
>       - "5900:5900"
>     shm_size: 128M
> ```
> and it should work fine!

I've tried the code (btw there's a typo in the command line - "/code/docker_quickst.py"]), but now I get this new error:

ERROR: for selenium  Cannot create container for service selenium: Conflict. The container name "/selenium" is already in use by container "4aeed8953f39697452ffb9b4608e02dc513e51046279b5a153d6fc439d3d0dcf". You have to remove (or rename) that container to be able to reuse that name.

**Comment by filo87** [comment]
Oops, looks like I missed a part of code while copy pasting....

try this one out and let me know...

```
version: '3'
services:
  web:
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./:/code
    command: ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "/code/docker_quickstart.py"]
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
```
