### ISSUE TITLE
Persist log data between docker containers

### ISSUE THREAD

**Issue by tobyf93** [InstaPy/InstaPy#686]
Absolutely love the decision to introduce docker into this project.  Big thumbs up from me!  However, i've noticed that log files don't persist between container instances.  This means that InstaPy will write important files like username_followedPool.csv to the containers filesystem but that is lost as soon as the container is rebuilt.

Suggested fixes for docker-compose.yml and docker-prod.yml:
```
version: '3'
services:
  web:
    volumes:
      - ./logs:/code/logs
...
```

You don't experience this issue using docker-dev.yml as that already mounts the whole project directory to `/code` in the container.

Let me know your feedback, happy to submit a pull request 👍
